[workspace]
resolver = "2"
members = ["wgpu-in-app", "app-surface", "cargo-so"]
default-members = ["wgpu-in-app"]

[workspace.dependencies]
bytemuck = { version = "1.14", features = ["derive"] }
cfg-if = "1.0"
glam = "0.25"
log = "0.4"
noise = { version = "0.8", default-features = false }
pollster = "0.3"
rand = "0.7.2"
wgpu = "0.19.3"
# wgpu = { git = "https://github.com/gfx-rs/wgpu", rev = "445fa6019b47079c9d336881dbee1c3be3ed4c38" }
# wgpu = { git = "https://github.com/jinleili/wgpu", branch="visionOS" }
async-executor = "1.6"
winit = { version = "0.29.10" }
raw-window-handle = "0.6"
env_logger = "0.10"

# macOS, iOS
libc = "0.2"
objc = "0.2.7"
core-graphics = "0.23.1"

# android target
android_logger = "0.13"
jni = "0.21"
jni_fn = "0.1"
ndk-sys = "0.4.1"
ash = "0.37.3"

# wasm target
web-sys = "0.3.67"
wasm-bindgen = "0.2.87"
js-sys = "0.3.67"
wasm-bindgen-futures = "0.4.40"
